server:
  port: 8090

spring:
  application:
    name: "loans"
  profiles:
    active: "default"
  config:
    import: "optional:configserver:http://localhost:8071/"
  datasource: # after, this will be written by Kubernates envs
    url: jdbc:mysql://localhost:3307/sbdb-db-loans
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health: # libera os endpoints para readness e liveness que serão usados para verificar se microsserviço está operante (...8071/actuator/health)
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint: # for deregister from eureka server when the microservice shutdown
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info: # info related actuator url
    env:
      enabled: true

endpoints: # for deregister from eureka server when the microservice shutdown
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info: # eureka server dashboard info
  app:
    name: "loans"
    description: "Spring Boot Demo Bank - Microservice - Loans"
    version: "1.0.0"

logging:
  level:
    com:
      artcorb:
        loans: DEBUG
